const ACTION_TYPE = {
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
  USER_REGISTRATION: 'USER_REGISTRATION',
  USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  GET_USER_INPUT: 'GET_USER_INPUT',
  GET_QUESTION_INPUT: 'GET_QUESTION_INPUT',
  POST_A_QUESTION_SUCCESS: 'POST_A_QUESTION_SUCCESS',
  POST_A_QUESTION_FAILURE: 'POST_A_QUESTION_FAILURE',
  GET_ALL_QUESTIONS: 'GET_ALL_QUESTIONS',

};

export default ACTION_TYPE;
